"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { list } from 'postcss';
import React from 'react';
import Navbar from './Navbar';
import Footer from './Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <main>
        <body className={inter.className}>
              <Navbar />
              <div className='flex flex-col space-y-10 relative top-24'>
                <div>
                  {children}
                <p>hello</p>
                </div>
                <div className=''>
                  <Footer />
                </div>
            </div>
        </body>
    </main>
  )
}

