import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';
import Navbar from './Navbar';
import Footer from './Footer';
import localFont from 'next/font/local'

const inter = localFont({src: '../public/fonts/nfs.ttf'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html>
        <body className={inter.className}>
        <Navbar />
          {children}
        <Footer />
        </body>
      </html>
  )
}

